name: Mirror Repository to AWS CodeCommit

inputs:
  role-to-assume:
    required: true

  repository:
    required: false
    default: ${{ github.repository }}
  
  codecommit-repository:
    required: false

  aws-region:
    required: false
    default: eu-west-1

runs:
  using: composite

  steps:
    - uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Mirror repository
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        CODECOMMIT_REPOSITORY: ${{ inputs.codecommit-repository }}
        GH_TOKEN: ${{ github.token }}
      run: |
        bash "$GITHUB_ACTION_PATH/mirror.sh"
